version: '3.8'

services:
  base_image:
    image: ${DOCKER_HUB}/${IMAGE_NAMESPACE}/server-dashboard-base:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
